providers = ["python"]

[variables]
  NIXPACKS_PYTHON_VERSION = "3.12"
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"

[phases.setup]
  nixPkgs = ["...", "chromium", "chromedriver", "nss"]

[phases.install]
  cmds = ["python -m venv /opt/venv", ". /opt/venv/bin/activate", "pip install -r requirements.txt"]

[start]
  cmd = "bash start.sh"
