# Generated by Django 5.1.7 on 2026-03-13 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('folder', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('capital_active', models.FloatField(default=0.0)),
                ('cap_value', models.FloatField(default=0.0)),
                ('cap_ingresado', models.FloatField(default=0.0)),
                ('cap_to_add', models.FloatField(default=0.0)),
                ('cap_retirado', models.FloatField(default=0.0)),
                ('pnl_real', models.FloatField(default=0.0)),
                ('pnl_unreal', models.FloatField(default=0.0)),
                ('rets', models.FloatField(default=0.0)),
                ('tg_key1', models.CharField(blank=True, max_length=255, null=True)),
                ('tg_key2', models.CharField(blank=True, max_length=255, null=True)),
                ('tp', models.FloatField(default=0.0)),
                ('sl', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('folder', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BotAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operate', models.BooleanField(default=True)),
                ('asset', models.CharField(max_length=255)),
                ('params1', models.CharField(blank=True, max_length=255, null=True)),
                ('params2', models.CharField(blank=True, max_length=255, null=True)),
                ('params3', models.CharField(blank=True, max_length=255, null=True)),
                ('alloc', models.FloatField(default=0.0)),
                ('broker', models.CharField(max_length=100)),
                ('position', models.IntegerField(default=0)),
                ('qty_open', models.FloatField(default=0.0)),
                ('cap_to_trade', models.FloatField(default=0.0)),
                ('cap_to_add', models.FloatField(default=0.0)),
                ('cap_value_in_trade', models.FloatField(default=0.0)),
                ('op_price', models.FloatField(default=0.0)),
                ('last_price', models.FloatField(default=0.0)),
                ('pnl_un', models.FloatField(default=0.0)),
                ('capAdded', models.FloatField(default=0.0)),
                ('PNL', models.FloatField(default=0.0)),
                ('trades', models.FloatField(default=0.0)),
                ('coms', models.FloatField(default=0.0)),
                ('since', models.CharField(blank=True, max_length=100, null=True)),
                ('cur_date', models.CharField(blank=True, max_length=100, null=True)),
                ('stats1', models.CharField(blank=True, max_length=255, null=True)),
                ('stats2', models.CharField(blank=True, max_length=255, null=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='botops.bot')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='botops.family')),
            ],
        ),
        migrations.AddField(
            model_name='bot',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to='botops.family'),
        ),
    ]
