# Generated by Django 5.1.7 on 2026-03-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='cap_no_asignado',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='botasset',
            name='stats1',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='botasset',
            name='stats2',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
