# Generated by Django 5.1.7 on 2026-03-13 03:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botops', '0002_bot_cap_no_asignado_alter_botasset_stats1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botasset',
            name='cur_date',
        ),
        migrations.RemoveField(
            model_name='botasset',
            name='since',
        ),
        migrations.AddField(
            model_name='botasset',
            name='created_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='botasset',
            name='updated_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
