# Generated by Django 5.1.7 on 2026-03-14 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botops', '0003_remove_botasset_cur_date_remove_botasset_since_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=255)),
                ('ochl', models.JSONField(blank=True, null=True)),
                ('ochl_last_update', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
