# Generated by Django 5.1.7 on 2026-03-14 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botops', '0004_assetseries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetseries',
            name='ochl_last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
