# Generated by Django 5.1.7 on 2026-03-14 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botops', '0005_alter_assetseries_ochl_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='strategy_type',
            field=models.CharField(choices=[('OneStrategy', 'OneStrategy'), ('MultiStrategy', 'MultiStrategy')], default='OneStrategy', max_length=20),
        ),
    ]
