# Generated by Django 5.1.7 on 2026-03-14 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botops', '0006_bot_strategy_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('coms', models.FloatField(default=1)),
            ],
        ),
    ]
