# Generated by Django 5.1.7 on 2026-03-14 03:00

from django.db import migrations, models
import django.db.models.deletion
import django


def link_brokers(apps, schema_editor):
    BotAsset = apps.get_model('botops', 'BotAsset')
    Broker = apps.get_model('botops', 'Broker')
    
    # Create the default broker if it doesn't exist
    default_broker, _ = Broker.objects.get_or_create(id=1, defaults={'name': 'hapi', 'coms': 1.0})

    for asset in BotAsset.objects.all():
        # Get or create the broker based on the existing string name (temporarily accessible before the AlterField)
        broker_name = str(asset.broker) if asset.broker else 'hapi'
        broker_obj, _ = Broker.objects.get_or_create(name=broker_name)
        
        # We can't assign directly to asset.broker if it's currently a string, 
        # but in Django migrations, we often need to use a temporary field or rely on the final state.
        # Since SQLite is tricky with altering columns from string to FK directly, the safest way is to rename, add FK, then copy.

class Migration(migrations.Migration):

    dependencies = [
        ('botops', '0007_broker'),
    ]

    operations = [
        # 1. Rename the old string field
        migrations.RenameField(
            model_name='botasset',
            old_name='broker',
            new_name='broker_old',
        ),
        # 2. Add the new ForeignKey field, temporarily nullable
        migrations.AddField(
            model_name='botasset',
            name='broker',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='assets',
                to='botops.broker'
            ),
        ),
        # 3. Create a RunSQL to manually stitch the data (since SQLite works well with raw SQL for this scenario)
        migrations.RunSQL(
            sql="""
            INSERT INTO botops_broker (name, coms) 
            SELECT DISTINCT broker_old, 1.0 FROM botops_botasset 
            WHERE broker_old NOT IN (SELECT name FROM botops_broker);
            
            UPDATE botops_botasset 
            SET broker_id = (SELECT id FROM botops_broker WHERE botops_broker.name = botops_botasset.broker_old);
            """,
            reverse_sql="UPDATE botops_botasset SET broker_old = (SELECT name FROM botops_broker WHERE id = broker_id);"
        ),
        # 4. Make the new FK non-nullable using AlterField
        migrations.AlterField(
            model_name='botasset',
            name='broker',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='assets',
                to='botops.broker'
            ),
        ),
        # 5. Remove the old field
        migrations.RemoveField(
            model_name='botasset',
            name='broker_old',
        ),
    ]
