# Generated by Django 5.1.7 on 2026-03-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botops', '0008_convert_broker_to_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summer', models.BooleanField(default=True)),
                ('start_hour', models.IntegerField(default=8)),
                ('end_hour', models.IntegerField(default=16)),
            ],
        ),
    ]
