# Generated by Django 5.1.7 on 2026-03-17 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botops', '0009_generalsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='execute_minute',
            field=models.IntegerField(default=55),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='operate_hour',
            field=models.IntegerField(default=15),
        ),
    ]
