# Generated by Django 5.1.7 on 2026-03-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botops', '0010_generalsettings_execute_minute_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalsettings',
            name='execute_minute',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='operate_hour',
        ),
        migrations.AddField(
            model_name='bot',
            name='execute_minute',
            field=models.IntegerField(default=55),
        ),
    ]
