# Generated by Django 5.1.7 on 2026-03-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botops', '0011_remove_generalsettings_execute_minute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='summer_operate_hour',
            field=models.IntegerField(default=14),
        ),
        migrations.AddField(
            model_name='bot',
            name='winter_operate_hour',
            field=models.IntegerField(default=13),
        ),
    ]
