# Generated by Django 5.1.7 on 2026-03-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botops', '0012_bot_summer_operate_hour_bot_winter_operate_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetseries',
            name='ochl_history',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='strategy_type',
            field=models.CharField(choices=[('OneStrategy', 'OneStrategy'), ('MultiStrategy', 'MultiStrategy'), ('FollowPrice', 'FollowPrice'), ('SignalDollar', 'SignalDollar'), ('SignalOptions', 'SignalOptions')], default='OneStrategy', max_length=20),
        ),
    ]
