# Generated by Django 5.1.7 on 2026-03-18 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botops', '0013_assetseries_ochl_history_alter_bot_strategy_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botasset',
            name='family',
        ),
    ]
