# Generated by Django 5.1.7 on 2026-03-19 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botops', '0014_remove_botasset_family'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_capital_added', models.FloatField(blank=True, default=0.0, null=True)),
                ('posterior_capital_added', models.FloatField(blank=True, default=0.0, null=True)),
                ('capital', models.FloatField(default=0.0)),
                ('add_withdraw', models.IntegerField(default=1)),
                ('date', models.DateField(blank=True, null=True)),
                ('assetbot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='botops.botasset')),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='botops.bot')),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='botops.broker')),
            ],
        ),
    ]
