# Generated by Django 5.1.7 on 2026-03-28 23:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botops', '0015_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='cap_to_add',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='cap_value',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='capital_active',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='pnl_real',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='pnl_unreal',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='rets',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='sl',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='tp',
        ),
        migrations.CreateModel(
            name='PortfolioHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('capital', models.FloatField(default=0.0)),
                ('chg_log', models.FloatField(default=0.0)),
                ('log_cum_sum', models.FloatField(default=0.0)),
                ('ret_cums', models.FloatField(default=0.0)),
                ('cagr', models.FloatField(default=0.0)),
                ('spy_price', models.FloatField(blank=True, null=True)),
                ('spy_ret', models.FloatField(blank=True, default=0.0, null=True)),
                ('qqq_price', models.FloatField(blank=True, null=True)),
                ('qqq_ret', models.FloatField(blank=True, default=0.0, null=True)),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='botops.bot')),
            ],
        ),
    ]
