# Generated by Django 5.1.7 on 2026-03-29 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botops', '0016_remove_bot_cap_to_add_remove_bot_cap_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetseries',
            name='fin_metrics_series',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
