# Generated by Django 5.1.7 on 2026-04-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botops', '0019_simplify_history_benchmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='botasset',
            name='capWithdrew',
            field=models.FloatField(default=0.0),
        ),
    ]
