# Generated by Django 5.1.7 on 2026-04-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botops', '0020_botasset_capwithdrew'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='move_between_bots',
            field=models.BooleanField(default=False),
        ),
    ]
