# Generated by Django 5.1.7 on 2026-04-09 02:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botops', '0021_transaction_move_between_bots'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliohistory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
