# Generated by Django 5.1.7 on 2026-05-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botops', '0022_portfoliohistory_created_at_transaction_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='botasset',
            name='cap_lever',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='botasset',
            name='leverage',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='bot',
            name='strategy_type',
            field=models.CharField(choices=[('OneStrategy', 'OneStrategy'), ('MultiStrategy', 'MultiStrategy'), ('FollowPrice', 'FollowPrice'), ('SignalDollar', 'SignalDollar'), ('SignalOptions', 'SignalOptions'), ('CrossAssetsOneSt', 'CrossAssetsOneSt')], default='OneStrategy', max_length=20),
        ),
    ]
