# Generated by Django 5.1.7 on 2026-03-29 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GemScrapperTactics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('params', models.JSONField(blank=True, null=True)),
                ('market_cap_category', models.CharField(default='all', max_length=255)),
                ('overall_weights', models.JSONField(blank=True, null=True)),
                ('value_weights', models.JSONField(blank=True, null=True)),
                ('quality_weights', models.JSONField(blank=True, null=True)),
                ('trend_weights', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_executed', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='completed', max_length=50)),
                ('tactic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='gemsfinder.gemscrappertactics')),
            ],
        ),
        migrations.CreateModel(
            name='SelectedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('sector', models.CharField(blank=True, max_length=255, null=True)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('market_cap', models.CharField(blank=True, max_length=255, null=True)),
                ('score', models.FloatField(default=0.0)),
                ('raw_metrics', models.JSONField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='gemsfinder.scrapingsession')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitorAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('raw_metrics', models.JSONField(blank=True, null=True)),
                ('target_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='gemsfinder.selectedasset')),
            ],
        ),
    ]
