# Generated by Django 5.1.7 on 2026-03-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemsfinder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedasset',
            name='score',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
