# Generated by Django 5.1.7 on 2026-04-18 04:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('botops', '0022_portfoliohistory_created_at_transaction_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metrics', models.JSONField(blank=True, null=True)),
                ('distributions', models.JSONField(blank=True, null=True)),
                ('equity_curve', models.JSONField(blank=True, null=True)),
                ('bh_curve', models.JSONField(blank=True, null=True)),
                ('drawdown_curve', models.JSONField(blank=True, null=True)),
                ('bot_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtests', to='botops.botasset')),
            ],
        ),
    ]
