# Generated by Django 5.1.7 on 2026-09-17 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SectorScreenerCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='default_screener', max_length=100, unique=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('tickers_list', models.JSONField(blank=True, default=list)),
                ('summary_data', models.JSONField(blank=True, null=True)),
                ('daily_prices', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
